# Generated by Django 4.2.7 on 2026-01-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('general', 'General Inquiry'), ('blinds', 'Window Blinds'), ('shades', 'Roller/Solar Shades'), ('motorized', 'Motorized Solutions'), ('commercial', 'Commercial Project'), ('custom', 'Custom Window Treatments')], default='general', max_length=50)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
